Runpathdirs improvements
premake/premake-core pull request #1538
Opened 2020-10-22 14:00 UTC by noresources

**What does this PR do?**
Fix and improve run path search paths support on gmake actions. Add support for xcode4

**How does this PR change Premake's behavior?**
Automatically added run path search paths from sibling library is now handled by exporters instead of toolset. The previous behavior may not be accurate for all build system.

Are there any breaking changes? Will any existing behavior change?
Not really, only gmake 1&2 supported runpathdirs and the behavior did not change for these exporters.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

2020-10-28 13:31 UTC, starkos commented
I'm a little uncomfortable adding run paths to a project that weren't explicitly requested by the user (the sibling projects). This probably needs an API similar to `links()` which allows sibling projects to be specified along with file system paths? I'll let @samsinsane (and anyone else who wants to review) have a say, but I'd vote against this one as-is.

2021-03-07 16:11 UTC, noresources commented
Currently, runpathdirs of sibling project are already automatically added. This patch just move this benavior to gmake action instead of gcc/clang code to ensure other actions are not affected. Please consider this PR as a code cleanup rather than a new feature.

As a reminder, this automatic behavior was previously added to fix the fact that binaries and libs generated by gmake actions cannot be moved from where they were built (library installation paths are hardcoded in the library binary on Linux & macOS). 

By the way, my initial proposal (years ago) for this was to add a `linkmode` API to let user choose between default install names (hardcoded) and automatic with runpaths etc.
The current solution was preferred :)

2021-03-10 10:36 UTC, samsinsane requested changes

2021-03-10 10:36 UTC, samsinsane commented on src/tools/gcc.lua
> +--    - "patn" List of path relative to configuration target directory
```suggestion
--    - "path" List of path relative to configuration target directory
```

2021-04-15 12:13 UTC, starkos requested changes
Thank you for clarifying, I see what you mean now. Would it be possible to rebase this one against the current master branch? And then I go ahead and approve it.

2021-04-16 17:02 UTC, noresources commented
The branch was rebased with a bit of commit history cleanup plus runpath support for xcode4

2021-04-19 14:58 UTC, starkos approved these changes
Thanks!

2021-04-19 14:58 UTC, merged