Rework website home & download pages
premake/premake-core pull request #1602
Opened 2021-03-23 14:37 UTC by starkos

**What does this PR do?**

Reworks the placeholder home and download pages on the new Docusaurus-based website.

**How does this PR change Premake's behavior?**

No changes to Premake itself.

**Anything else we should know?**

I still need to rework the header and footer, and move some content from `docs/` to `pages/` such as the help and "who uses" pages. Tracking the work on #1547.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] ~Add unit tests showing fix or feature works; all tests pass~
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

2021-03-23 21:50 UTC, KyrietS requested changes
> I still need to rework the header and footer, and move some content from docs/ to pages/ such as the help and "who uses" pages.

Just a reminder that you can create simple pages in Markdown. Docusaurus will take care of it. You don't have to use JS and React in every page.

2021-03-23 21:50 UTC, KyrietS commented on website/src/pages/download.js
> +						</p>
`<div>` cannot appear as a descendant of `<p>`. You will see this error when you go to download page and open console in your browser. It's not react error. Website is compiled correctly but accorting to W3C you cannot put *block elements* inside `<p>` and React is kind enough to report this in the console.

My suggestion here is to change this paragraph with `DownloadLink`s into list `<ul>`, `<li>` then add a class to `<ul>`, e.g. "download-links" and style it. (then you can remove "download-link" class from `DownloadLink`). Unlike `<p>`, lists can contain *divs* and other *block elements*.

* To remove list bullets use: `list-style: none;`
* You can also style each item in the list: `.download-links > li { /*...*/ }`

2021-03-23 21:50 UTC, KyrietS commented on website/src/pages/download.js
> +						</p>
Same problem as above. I suggest using list with one item. Left padding is natural in lists. You don't have to create it artificially for every `DownloadLink`.

2021-03-23 21:50 UTC, KyrietS commented on website/src/pages/download.js
> +		</div>
I don't think that using `div` here and styling it in this way is a good idea. I suggest removing `div` so the  `Link` becomes the top element. To understand my point of view please look at my comments below.

2021-03-23 21:50 UTC, KyrietS commented on website/src/pages/index.js
> +	</div>;
I suggest using `<Column> </Column>` here. It's already imported but it's not used (yet).

2021-03-24 14:44 UTC, starkos commented
Good feedback, thanks! I was going back and forth on the layout of the download links and didn't clean things up properly; I've switched them to `<ul>` as suggested. I'm hoping/intending to loop back and associate icons with each one at some point (why I wrapped them in `<div>`).

Console errors are gone. I also backed out my formatting change to `docusaurus.config.js` to avoid conflicts with your commit.

2021-03-24 20:06 UTC, KyrietS approved these changes
Thanks for the changes you've made. It looks great now. Those `DownloadLink` lists still can be simplified and refactored but it's good enough to merge this commit in my opinion.

And I wouldn't worry about conflicts in `docusaurus.config.js`. I can always do rebase and force-push to my branch :-)

2021-03-25 17:43 UTC, merged