Sort `buildinputs` and `buildoutputs` on xcode4
premake/premake-core pull request #1631
Opened 2021-05-26 02:59 UTC by tempura-sukiyaki

**What does this PR do?**

Fixed a issue where xcodeproj would be modified even if the Premake script was not modified if multiple paths were specified for `buildinputs` or `buildoutputs`.

**How does this PR change Premake's behavior?**

The above issue was caused by an indeterminate sort order of Lua's key-value tables, so that part has been fixed.

**Anything else we should know?**

None.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [ ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [ ] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

2021-05-29 12:16 UTC, samsinsane commented
Do the other generators sort these too? We should try to be consistent.

Also, is there a case where a user wouldn't want the inputs to be sorted, but instead in the order they specified?

2021-05-29 17:49 UTC, starkos requested changes
Full agreement that the order needs to be deterministic, but think the ideal option is to output them in the same order in which they appear in the source script. Simple fix: just replace `table.insertsorted()` with `table.insert()` and adjust the tests. If you agree and can make that change, we can get this one merged. Thanks for taking the time to tackle this!

2021-06-04 07:02 UTC, samsinsane approved these changes

2021-06-07 22:03 UTC, starkos approved these changes

2021-06-07 22:03 UTC, merged