Deprecate configuration()
premake/premake-core pull request #1718
Opened 2021-09-16 14:29 UTC by starkos

**What does this PR do?**

Marks `configuration()` as deprecated. We'll continue supporting it for 5.0, but it will not be included in Premake 6.

**How does this PR change Premake's behavior?**

No breaking changes, just a warning message.

**Anything else we should know?**

Nope.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] ~~Add unit tests showing fix or feature works; all tests pass~~ (n/a)
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

2021-09-16 21:52 UTC, nickclark2016 approved these changes

2021-09-17 00:51 UTC, KyrietS requested changes
As it's officialy deprecated now, I'd suggest aligning all the examples that use `configuration` instead of `filter`.

I think I've listed all of them:

* [x] [buildoptions](https://premake.github.io/docs/buildoptions/)
* [x] [Command Line Arguments](https://premake.github.io/docs/Command-Line-Arguments/)
* [x] [debugargs](https://premake.github.io/docs/debugargs/)
* [ ] [debugdir](https://premake.github.io/docs/debugdir/)
* [ ] [implibsuffix](https://premake.github.io/docs/implibsuffix/)
* [ ] [linkoptions](https://premake.github.io/docs/linkoptions/)
* [ ] [links](https://premake.github.io/docs/links/)
* [ ] [postbuildcommands](https://premake.github.io/docs/postbuildcommands/)
* [ ] [prebuildcommands](https://premake.github.io/docs/prebuildcommands/)
* [ ] [prelinkcommands](https://premake.github.io/docs/prelinkcommands/)
* [ ] [resoptions](https://premake.github.io/docs/resoptions/)
* [ ] [targetdir](https://premake.github.io/docs/targetdir/)
* [ ] [targetsuffix](https://premake.github.io/docs/targetsuffix/)

2021-09-17 10:48 UTC, starkos commented
> I'd suggest aligning all the examples that use configuration instead of filter. I think I've listed all of them:

@KyrietS I so appreciate having you on the project. Fixed now.

2021-09-17 14:41 UTC, KyrietS approved these changes

2021-09-17 18:04 UTC, merged