Updated Bug Report Template to add exporter selection
premake/premake-core pull request #1900
Opened 2022-06-25 23:28 UTC by nickclark2016

**What does this PR do?**

Adds a selection for the bug report template to allow users to select the exporter they experience the bug on.

**How does this PR change Premake's behavior?**

No breaking changes.

**Anything else we should know?**

This will be useful in the future for more quickly hunting down bugs, especially for tooling with multiple versions supported.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

2022-06-28 19:32 UTC, KyrietS approved these changes

2022-07-12 13:01 UTC, samsinsane requested changes
While I can see benefit to knowing this information, this should already be part of "how can we reproduce this". Perhaps this section should be expanded with more context instead of a new section that splits the information up.

Additionally, a breakdown of exporters (or anything else) should give _us_ more context. Due to the way the VS exporter code is split up, grouping older versions together like this doesn't give us more context. I know why you've done the split like this but it's eliminating the value of asking for the information when it comes to older versions of VS.

2022-07-12 13:26 UTC, nickclark2016 commented on .github/ISSUE_TEMPLATE/report-a-bug.md
> +- [ ] Visual Studio 2019 (vs2022)
Good catch. I'll get that updated.

2022-07-12 13:32 UTC, nickclark2016 commented
So it sounds like the course of action is to move the exporters to the "how can we reproduce this section" instead of a new section and adding VS2005 - VS2017 into the options.  I just find myself asking this question too often to not have a field for it.

2022-08-01 07:44 UTC, samsinsane approved these changes

2022-08-01 07:45 UTC, merged