Update usefullpaths.md
premake/premake-core pull request #1981
Opened 2022-10-12 11:55 UTC by nepp95

**What does this PR do?**

Updates [this](https://premake.github.io/docs/usefullpaths) page, which was auto generated.

**How does this PR change Premake's behavior?**

Website update, no changes to Premake itself.

**Anything else we should know?**

Only tested in Visual Studio 2022, but left the defaults for availability.

Related PR: #1571

2022-10-12 12:28 UTC, nickclark2016 requested changes

2022-10-12 12:28 UTC, nickclark2016 commented on website/docs/usefullpaths.md
> +usefullpaths "switch"
Most of the On/Off toggle-able values are `("value")` in documentation, so that should probably match.

2022-10-12 12:28 UTC, nickclark2016 commented on website/docs/usefullpaths.md
> +| Option      | Availability                |
Instead of availability, these should be descriptions. See `pic` docs, for example.

2022-10-12 18:25 UTC, nepp95 commented
Added requested changes.

2022-10-23 06:14 UTC, samsinsane approved these changes

2022-10-31 21:24 UTC, nickclark2016 approved these changes

2022-11-28 20:07 UTC, KyrietS commented
@nepp95 please squash your commits into one if you want to be marked as the author of your changes on our website.

1. Go to your repo and checkout your branch `patch-1`: `git checkout patch-1`
2. `git reset --soft master`
3. `git add .`
4. `git commit -m "Update usefullpaths.md"`
5. `git pull -r`
6. `git push --force`

2022-11-29 09:42 UTC, nepp95 commented
> 

For some reason, those steps don't work for me.
You can squash it for me, doesn't really matter to me, although I am interested in if I did something wrong for future pull requests :)

![Screenshot 2022-11-29 104132](https://user-images.githubusercontent.com/4678993/204494246-735d1a70-783d-4d29-9044-1645dd205354.png)

2022-11-29 11:24 UTC, nepp95 commented
Managed to squash it. Learned another lesson.

```
git rebase -i HEAD~3
git push --force
```

2022-12-01 17:03 UTC, KyrietS commented
> > 
> 
> @KyrietS For some reason, those steps don't work for me. You can squash it for me, doesn't really matter to me, although I am interested in if I did something wrong for future pull requests :)
> 

You forgot about `git commit` step, but I'm happy that you've managed to squash it 😄

2022-12-01 17:28 UTC, merged