Update defaultplatform.md
premake/premake-core pull request #1985
Opened 2022-10-19 15:17 UTC by GiacomoMaino

**What does this PR do?**

This PR adds the documentation for defaultplatform as there was only the automatically generated empty one.

**How does this PR change Premake's behavior?**

It doesn't.

**Anything else we should know?**

I tested the behaviour of defaultplatform extensively only with the gmake2 as the Makefile was giving problems.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Add unit tests showing fix or feature works; all tests pass - Does not apply
- [ ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged) - Does not apply
- [ ] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions) - Does not apply
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

2022-10-20 16:10 UTC, KyrietS requested changes
Thanks for your contribution! I added some comments requesting minor changes.

Please use `--amend` when you commit the fixes 🙂

2022-10-20 16:10 UTC, KyrietS commented on website/docs/defaultplatform.md
>  ```
At the end add:
```
### See Also ###

* [defaultplatform](defaultplatform.md)
```

2022-10-24 15:37 UTC, GiacomoMaino commented
I'm sorry to be late, but I made the PR just before leaving and I just got home again.
It was my first time ammending a commit, so I hope to have done everything correctly.
Please, keep me posted.

2022-10-24 22:21 UTC, KyrietS approved these changes
You did great 👍 Now it's all good to me. I'll leave it for some time and then we'll merge your change

2022-10-25 16:07 UTC, GiacomoMaino commented
Thanks a lot for guiding me! I hope to be able to contribute again!

2022-10-25 18:08 UTC, KyrietS requested changes

2022-10-25 18:08 UTC, KyrietS commented on website/docs/defaultplatform.md
> +* [defaultplatform](defaultplatform.md)
Oh no, I am so sorry! 😅 I asked you to add:
```
* [defaultplatform](defaultplatform.md)
```

but of course what I meant was:
```
* [platforms](platforms.md)
```

Please do this one last fix 😄

You can also add `* [defaultplatform](defaultplatform.md)` to [platforms.md](https://github.com/premake/premake-core/blob/master/website/docs/platforms.md) so these pages link each other as they are related.

2022-10-26 12:19 UTC, GiacomoMaino commented
I hope to have done verything as it should be done.
I thought it was bizarre but I didn't dare to ask. 😓
If I need to change anything else let me know!

2022-10-29 15:57 UTC, KyrietS commented
Don't be afraid to challenge my ideas 😄
I can see that you've made another 3 commits. We try to minimize the number of commits if the change is small. In your case we should have one commit. So either you squash the commits on your branch into one or I will squash it doing merge, but then you won't be listed as an author of the change in our repo (it would be me, who click the merge button).

I will give you one more day to squash your commits. Here is what you need to do in case you're not very good at git 🙃

1. Go to your repo and checkout your branch `patch-1`: `git checkout patch-1`
2. `git reset --soft master`
3. `git add .`
4. `git commit -m "Update defaultplatform.md"`
5. `git push --force`

2022-10-31 17:26 UTC, GiacomoMaino commented
I followed your instructions very carefully. I'm not sure if I had to do two commits though as I added the reference to defaultplatform.md to platforms.md.

I hope it's good now, for anything I will try again. Thank you for your patience.😓

2022-10-31 20:47 UTC, KyrietS approved these changes
Good job 👍 
Thanks for contributing to Premake's docs 🤗

2022-10-31 20:47 UTC, merged