Add Library to available shadertypes
premake/premake-core pull request #2217
Opened 2024-06-11 16:25 UTC by vkaytsanov

**What does this PR do?**

Adds a Library shadertype to the options when having hlsl shaders in the project

**How does this PR change Premake's behavior?**

It doesn't

**Anything else we should know?**

Nothing

**Did you check all the boxes?**

- [ V] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ X] Add unit tests showing fix or feature works; all tests pass
- [X ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [V ] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [V ] Minimize the number of commits
- [ V] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

2024-06-15 18:48 UTC, Jarod42 requested changes
- website\docs\shadertype.md should be updated (doc)

2024-06-15 18:49 UTC, Jarod42 commented
[OT]: `[x]` for checked, and `[ ]` unchecked, it is not `[V]` and `[ X]`.

2024-06-16 00:43 UTC, Jarod42 approved these changes

2024-07-20 18:18 UTC, nickclark2016 approved these changes

2024-08-07 16:33 UTC, Jarod42 commented
Asked on [stackoverflow.com](https://stackoverflow.com/questions/78797491/premake-shader-libraries)

2024-08-30 07:24 UTC, merged