Add `os.getnumcpus` function to get number of logical CPU cores.
premake/premake-core pull request #2241
Opened 2024-09-01 17:07 UTC by tritao

**What does this PR do?**

Adds a new `os.getnumcpus` API to get the number of logical CPU cores.

This can be helpful to know the parameter to pass to `make -j` flag, which in my case I need to generate correct VS Code tasks files. 

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

2024-09-01 17:30 UTC, KyrietS requested changes

2024-09-01 17:30 UTC, KyrietS commented on website/docs/os.getnumcpus.md
Please add this page to the [sidebar.js](https://github.com/premake/premake-core/blob/master/website/sidebars.js) (os category)

2024-09-01 17:30 UTC, KyrietS commented on website/docs/os.getnumcpus.md
> +cwd = os.getnumcpus()
`cwd = ...`

copy&paste from [`os.getcwd`](https://premake.github.io/docs/os.getcwd)? Busted! 😄

2024-09-01 23:39 UTC, Jarod42 commented on src/host/os_getnumcpus.c
> + * \author Copyright (c) 2002-2008 Jason Perkins and the Premake project
Wrong year ;-)

2024-09-01 23:39 UTC, Jarod42 commented on src/host/os_getnumcpus.c
> + * \file   os_getcwd.c
Wrong filename

2024-09-01 23:39 UTC, Jarod42 commented on src/host/os_getnumcpus.c
> + * \brief  Retrieve the current working directory.
Wrong description, copy paste is evil.

2024-09-01 23:39 UTC, Jarod42 commented on src/host/os_getnumcpus.c
> +			numCPU = 1;
Linux has `return 0;` on error, why not here?

2024-09-01 23:39 UTC, Jarod42 commented on src/host/os_getnumcpus.c
> +#include <sched.h>
Would it be simpler to `#define _GNU_SOURCE` here?
It even seems that `_POSIX_C_SOURCE=200809L` or `_XOPEN_SOURCE=700` are more appropriate.

2024-09-02 00:36 UTC, Jarod42 commented on website/docs/os.getnumcpus.md
> +Premake 5.0 or later.
```suggestion
Premake 5.0.0 beta 3 or later.
```

2024-09-02 21:04 UTC, Jarod42 approved these changes

2024-09-04 00:56 UTC, nickclark2016 requested changes
Pretty minor, fix and I'll merge.

2024-09-04 00:56 UTC, nickclark2016 commented on src/host/os_getnumcpus.c
> +#if PLATFORM_WINDOWS
We should explicitly include the windows header. Don't rely on transient includes.

2024-09-11 16:43 UTC, theComputeKid commented
Thanks for this! Previously, I had to use this code for my projects:
```
function getNumProc()
    if os.host() == "windows" then
        return os.getenv("NUMBER_OF_PROCESSORS")
    else
        output, errorCode = os.outputof("getconf _NPROCESSORS_ONLN")
        return output
    end
end
```

Now I can use the function you have added instead.

2024-09-11 17:39 UTC, KyrietS approved these changes

2024-09-11 21:04 UTC, nickclark2016 approved these changes

2024-09-11 21:04 UTC, merged