Fix `os.host` for Cosmopolitan build
premake/premake-core pull request #2284
Opened 2024-10-03 22:14 UTC by tritao

**What does this PR do?**

Fixes `os.host` for Cosmopolitan build

**Anything else we should know?**

Also a minor cleanup where `_TARGET_OS` is moved to Lua which would have prevented this bug in the first place.

Should we still leave an assignement to `_TARGET_ARCH = nil` just for documentation sake that it exists?

2024-10-04 03:23 UTC, samsinsane requested changes

2024-10-04 03:23 UTC, samsinsane commented on src/_premake_main.lua
> +		end
This seems unrelated to the rest of the PR?

2024-10-04 03:23 UTC, samsinsane commented on src/_premake_main.lua
> + 				print("Error: no such action '" .. _ACTION .. "'")
Accidental space at the start of the line?

2024-10-04 03:23 UTC, samsinsane commented on src/_premake_main.lua
> +
Seems unrelated to the rest of the PR?

2024-10-04 12:47 UTC, Jarod42 approved these changes

2024-10-06 03:57 UTC, samsinsane approved these changes

2024-10-06 03:57 UTC, merged