Release 5.0-beta4 prep
premake/premake-core pull request #2399
Opened 2024-12-28 16:03 UTC by nickclark2016

Release 5.0-beta4 prep. Snuck in a slight change to the badges in the README to use the GitHub CI jobs.

2024-12-29 09:41 UTC, Jarod42 approved these changes

2024-12-30 01:35 UTC, samsinsane requested changes

2024-12-30 01:35 UTC, samsinsane commented on CHANGES.txt
This file is supposed to be added to, you've replaced the beta3 changes.

2024-12-30 01:35 UTC, samsinsane commented on scripts/changes.lua
> +	print(cmd)
Is this meant to be here?

2024-12-30 02:09 UTC, samsinsane commented on CHANGES.txt
Please disregard this comment, I misread the changes. 🤦

2024-12-30 02:16 UTC, merged